version: "3"

vars:
    GOOS: "{{default OS .GOOS}}"
    MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
    DC_DIR: "deployment/docker-compose"
    INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"
    MONITORING_DC_FILE: "{{.DC_DIR}}/monitoring.yml"
    APP_DC_FILE: "{{.DC_DIR}}/apps.yml"
    SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'

tasks:
    default:
        cmds:
            - task: test

    test:
        deps:
            [format]
        cmds:
            - "{{.MVNW}} clean verify"

    format:
        cmds:
            - "{{.MVNW}} spotless:apply"

    build:
        cmds:
            - "{{.MVNW}} -pl config-server clean install -PbuildDocker -DskipTests"
            - "{{.MVNW}} -pl discovery-server clean install -PbuildDocker -DskipTests"
            - "{{.MVNW}} -pl catalog-service clean install -PbuildDocker -DskipTests"
            - "{{.MVNW}} -pl order-service clean install -PbuildDocker -DskipTests"
            - "{{.MVNW}} -pl notification-service clean install -PbuildDocker -DskipTests"
            - "{{.MVNW}} -pl api-gateway clean install -PbuildDocker -DskipTests"
            - "{{.MVNW}} -pl bookstore-webapp clean install -PbuildDocker -DskipTests"

    build_single:
        desc: "Build Docker image for a single service. Usage: task build_single SERVICE=config-server"
        cmds:
            - "{{.MVNW}} -pl {{.SERVICE}} clean install -PbuildDocker -DskipTests"

    ### Infrastructure ###
    start_infra:
        cmds:
            - "docker compose -f {{.INFRA_DC_FILE}} up -d"

    stop_infra:
        cmds:
            - "docker compose -f {{.INFRA_DC_FILE}} stop"
            - "docker compose -f {{.INFRA_DC_FILE}} rm -f"

    restart_infra:
        cmds:
            - task: stop_infra
            - task: sleep
            - task: start_infra

    ### Push image ###
    pushImages:
        cmds:
            - "docker push anhkhoa217/bookstore-config-server:latest"
            - "docker push anhkhoa217/bookstore-discovery-server:latest"
            - "docker push anhkhoa217/bookstore-order-service:latest"
            - "docker push anhkhoa217/bookstore-notification-service:latest"
            - "docker push anhkhoa217/bookstore-api-gateway:latest"
            - "docker push anhkhoa217/bookstore-webapp:latest"

    ### Monitoring ###
    start_monitoring:
        cmds:
            - "docker compose -f {{.MONITORING_DC_FILE}} up -d"

    stop_monitoring:
        cmds:
            - "docker compose -f {{.MONITORING_DC_FILE}} stop"
            - "docker compose -f {{.MONITORING_DC_FILE}} rm -f"

    restart_monitoring:
        cmds:
            - task: stop_monitoring
            - task: sleep
            - task: start_monitoring

    ### Main application ###
    start:
#        deps: [format, build]
        cmds:
            - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APP_DC_FILE}} up -d"

    stop:
        cmds:
            - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APP_DC_FILE}} stop"
            - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APP_DC_FILE}} rm -f"

    restart:
        cmds:
            - task: stop
            - task: sleep
            - task: start
    ### Chore: sleep ###
    sleep:
        vars:
            DURATION: "{{default 5 .DURATION}}"
        cmds:
            - "{{.SLEEP_CMD}} {{.DURATION}}"

    clean:
        cmds:
            - docker system prune -af
            - docker volume prune -af
