spring:
    application:
        name: api-gateway
    config:
        import: optional:configserver:http://localhost:8888/

server:
    port: 8989
    shutdown: graceful

---
spring:
    application:
        name: api-gateway
    config:
        activate:
            on-profile: docker
        import: configserver:http://config-server:8888

server:
    port: 8989
    shutdown: graceful
