name: "bookstore-microservices"
services:
  config-server:
    image: anhkhoa217/bookstore-config-server:latest
    container_name: config-server
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8888/actuator/health",
        ]
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  discovery-server:
    image: anhkhoa217/bookstore-discovery-server:latest
    container_name: discovery-server
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  catalog-service:
    image: anhkhoa217/bookstore-catalog-service:latest
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/catalog
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      catalog-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
    labels:
      logging: "promtail"

  order-service:
    image: anhkhoa217/bookstore-order-service:latest
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ORDERS_CATALOG_SERVICE_URL=http://api-gateway:8989/catalog
      - DB_URL=jdbc:postgresql://orders-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - OAUTH2_SERVER_URL=http://keycloak:9191
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/orders
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
      orders-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      discovery-server:
        condition: service_started
    labels:
      logging: "promtail"

  notification-service:
    image: anhkhoa217/bookstore-notification-service:latest
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://notifications-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
      notifications-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
      discovery-server:
        condition: service_started
    labels:
      logging: "promtail"

  api-gateway:
    image: anhkhoa217/bookstore-api-gateway:latest
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CATALOG_SERVICE_URL=http://catalog-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
    ports:
      - "8989:8989"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_started
    labels:
      logging: "promtail"

  frontend:
    image: anhkhoa217/bookstore-frontend:latest
    container_name: "bookstore-frontend"
    ports:
      - "80:80"
    depends_on:
      - api-gateway
