spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888/

eureka:
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85

server:
  port: 8761
  shutdown: graceful

---
spring:
  application:
    name: discovery-server
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

eureka:
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85

server:
  port: 8761
  shutdown: graceful