spring:
  application:
    name: bookstore-webapp
  config:
    import: optional:configserver:http://localhost:8888/

server:
  port: 8080
  shutdown: graceful

---
spring:
  application:
    name: bookstore-webapp
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

server:
  port: 8080
  shutdown: graceful