spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/kiin21/bookstore-microservices-config
                    default-label: main

server:
    port: 8888

management:
    endpoints:
        web:
            exposure:
                include: "*"

# Logging
logging:
    level:
        org.springframework.cloud.config: DEBUG